bash scripts/calculate_diff_score.sh peter_source results/peter_cyclegan_seq_diff_v2_1/test_50/fake
bash scripts/calculate_diff_score.sh peter_source results/peter_cyclegan_seq_diff_v2_1/test_80/fake
bash scripts/calculate_diff_score.sh peter_source results/peter_cyclegan_seq_diff_v2_1/test_100/fake
bash scripts/calculate_diff_score.sh peter_source results/peter_cyclegan_seq_diff_v2_1/test_120/fake
bash scripts/calculate_diff_score.sh peter_source results/peter_cyclegan_seq_diff_v2_1/test_150/fake
bash scripts/calculate_diff_score.sh peter_source results/peter_cyclegan_seq_diff_v2_1/test_180/fake
bash scripts/calculate_diff_score.sh peter_source results/peter_cyclegan_seq_diff_v2_1/test_200/fake
